export default {
  // genres
  FETCH_GENRES: 'FETCH_GENRES',
  FETCH_GENRES_PENDING: 'FETCH_GENRES_PENDING',
  FETCH_GENRES_FULFILLED: 'FETCH_GENRES_FULFILLED',
  FETCH_GENRES_REJECTED: 'FETCH_GENRES_REJECTED',

  // movies
  FETCH_MOVIES: 'FETCH_MOVIES',
  FETCH_MOVIES_PENDING: 'FETCH_MOVIES_PENDING',
  FETCH_MOVIES_FULFILLED: 'FETCH_MOVIES_FULFILLED',
  FETCH_MOVIES_REJECTED: 'FETCH_MOVIES_REJECTED',
}
